"""empty message

Revision ID: c90e0e8b4ef6
Revises: b1ea9aedf189
Create Date: 2020-06-16 22:10:37.767171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c90e0e8b4ef6'
down_revision = 'b1ea9aedf189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('code', sa.String(length=150), nullable=False))
    op.drop_column('transactions', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('token', mysql.VARCHAR(length=150), nullable=False))
    op.drop_column('transactions', 'code')
    # ### end Alembic commands ###
